permalink: "/:year/:month/:day/:title/"
markdown: "rdiscount"
exclude: ["Rakefile", "README.markdown", "Gemfile", "Gemfile.lock", "_secret.yml"]
source: "source"
destination: "public"
plugins: "plugins"
paginate: 10

replace_absolute: "/media/"
absolute_path: ""
root: "runthejewels.xyz"
instagram_client_id: "9ed4a700d97a44c588d5ea02eecae2fb"
instagram_redirect_uri: "http://run-the-jewels.github.io"
max_caption_created_diff: 600
